CUDA_VISIBLE_DEVICES=0 /home/dlth/miniconda3/envs/norm-base/bin/python /home/dlth/norm-exp-code/Norm-exp-base/PDE/pde.py \
 -a=MLP \
 --width=6 \
 --depth=4 \
 --batch_size=128 \
 --dropout=0 \
 --pde_type=helmholtz \
 --lr=1e-4 \
 --lr-method=step \
 --lr-step=5 \
 --lr-gamma=0.9 \
 --epochs=6000 \
 --norm=LN \
 --norm-cfg=num_per_group=4,dim=2 \
 --activation=tanh \
 --optimizer=sgd \
 --optimizer-config=momentum=0 \
 --weight-decay=0.0\
 --seed=1 \
 --log-suffix=base \
 --no_save_best \
 --display_every=10 \
 --metrics "l2 relative error,MSE" \
#  --visualize \
